Repository 2025-Summer-Bootcamp-TeamA/frontend, pull requests merged in 2025-07, with the labels that each got.

#15 [feat/#14] 도움말 화면(1,2,3)
  App.js
  assets/Onboarding/Onboarding1.png
  assets/Onboarding/Onboarding2.png
  assets/Onboarding/Onboarding3.png
  src/components/Home/MainFeatureCard.js
  src/components/Onboarding/OnboardingDescription.js
  src/components/Onboarding/OnboardingImage.js
  src/components/Onboarding/OnboardingIndicator.js
  src/components/Onboarding/OnboardingTemplate.js
  src/components/Onboarding/SkipButton.js
  src/components/Onboarding/XButton.js
  src/screens/Home/HomeScreen.js
  src/screens/Home/Onboarding.js
  src/screens/Home/Onboarding1.js
  src/screens/Home/Onboarding2.js
  src/screens/Home/Onboarding3.js
Labels: 🎨 Design, ✨ Feature

#17 영상 재생 화면
  app.json
  assets/backgrounds/frame.png
  assets/backgrounds/video_playback_background.png
  assets/icons/Demo1.png
  assets/icons/icon.png
  assets/icons/left.png
  assets/icons/play.png
  assets/icons/right.png
  package-lock.json
  package.json
  src/components/ArtworkInfoPanel.js
  src/components/PlayerControls.js
  src/screens/Library/VideoDetailScreen.js
Labels: ✨ Feature

#19 프로필화면 만들기
  App.js
  app.json
  assets/fonts/NotoSerif-Bold.ttf
  assets/fonts/NotoSerif-Regular.ttf
  package-lock.json
  package.json
  src/components/ProfileActions.js
  src/components/ProfileInfo.js
  src/components/ProfileStatItem.js
  src/components/ProfileStats.js
  src/components/ProfileTitle.js
  src/navigation/MainTabs.js
  src/screens/Profile/ProfileScreen.js
Labels: ✨ Feature

#27 [feat/#26] 화면 전환 시 배경 이미지 끊김 현상 개선
  assets/backgrounds/MainFeature 배경.webp
  src/components/Profile/ProfileStats.js
  src/screens/Home/HomeScreen.js
  src/screens/Home/PhotoUpload.js
  src/screens/Library/LibraryScreen.js
  src/screens/Profile/ProfileScreen.js
Labels: 🛠️ Refactor

#22 현재 박물관 선택 화면
  package-lock.json
  package.json
  src/components/Home/Museumchoosecard.js
  src/navigation/MainTabs.js
  src/screens/Home/MuseumListScreen.js
Labels: 🎨 Design, ✨ Feature

#34 [feat/#32] 카메라 화면 추가 및 사진 업로드 기능 개선, Redux 상태 관리 통합
  App.js
  app.json
  package-lock.json
  package.json
  src/components/photo_upload/Header.js
  src/components/photo_upload/PhotoRemoveModal.js
  src/components/photo_upload/PrimaryButton.js
  src/components/photo_upload/UploadCard.js
  src/screens/Home/CameraScreen.js
  src/screens/Home/LoadingScreen.js
  src/screens/Home/PhotoUpload.js
  src/store/photoSlice.js
  src/store/store.js
Labels: ✨ Feature
